-- Run this script in MySQL Workbench connected to your RDS instance
-- This creates the CRMRMD.leads table with all required fields

CREATE TABLE IF NOT EXISTS CRMRMD.leads (
  id                         VARCHAR(36)   NOT NULL PRIMARY KEY,
  record_type                VARCHAR(100)  DEFAULT 'Household Fresh',
  salutation                 VARCHAR(20),
  first_name                 VARCHAR(100),
  last_name                  VARCHAR(100),
  title                      VARCHAR(100),
  gender                     VARCHAR(20),
  birth_date                 DATE,
  age                        INT,
  age_group                  VARCHAR(50),
  education                  VARCHAR(100),
  occupation                 VARCHAR(100),
  income_range               VARCHAR(50),
  no_of_children             TINYINT       DEFAULT 0,
  phone                      VARCHAR(20),
  mobile                     VARCHAR(20),
  alternate_mobile           VARCHAR(20),
  alternate_mobile2          VARCHAR(20),
  email                      VARCHAR(200),
  alternate_email            VARCHAR(200),
  sms_mobile                 VARCHAR(20),
  house_no                   VARCHAR(50),
  floor_no                   VARCHAR(50),
  building_wing_tower        VARCHAR(100),
  society_apartment_name     VARCHAR(200),
  society_name               VARCHAR(200),
  street_colony_road         VARCHAR(200),
  landmark                   VARCHAR(200),
  pocket_block               VARCHAR(100),
  locality_name              VARCHAR(200),
  locality_code              VARCHAR(50),
  pincode                    VARCHAR(10),
  city                       VARCHAR(100),
  district                   VARCHAR(100),
  state                      VARCHAR(100),
  address                    TEXT,
  rmd_address                TEXT,
  company                    VARCHAR(200),
  industry                   VARCHAR(100),
  rating                     VARCHAR(20),
  website                    VARCHAR(255),
  vertical                   VARCHAR(50),
  order_type                 VARCHAR(50),
  lead_status                VARCHAR(50)   DEFAULT 'New',
  lead_source                VARCHAR(50),
  call_status                VARCHAR(50),
  visit_status               VARCHAR(50),
  interested                 VARCHAR(10),
  primary_contact            VARCHAR(50),
  pre_prospect_record_type   VARCHAR(100),
  publications               VARCHAR(200),
  branch_code                VARCHAR(20),
  depot_code                 VARCHAR(20),
  crm_email                  VARCHAR(200),
  owner_name                 VARCHAR(200),
  payee_name                 VARCHAR(200),
  agree_terms                TINYINT(1)    DEFAULT 0,
  opt_in                     TINYINT(1)    DEFAULT 0,
  is_converted               TINYINT(1)    DEFAULT 0,
  is_duplicate               TINYINT(1)    DEFAULT 0,
  is_institutional           TINYINT(1)    DEFAULT 0,
  is_serviceable             TINYINT(1)    DEFAULT 0,
  fresh_payment_flag         TINYINT(1)    DEFAULT 0,
  next_action_datetime       DATETIME,
  next_action_remarks        TEXT,
  appointment_datetime       DATETIME,
  interested_on_date         DATE,
  offer_valid_date           DATE,
  order_expiry_date          DATE,
  reason                     VARCHAR(200),
  interest                   VARCHAR(100),
  competition                VARCHAR(100),
  reason_for_lost            VARCHAR(200),
  renewal_payment_link       VARCHAR(500),
  short_renewal_payment_link VARCHAR(200),
  measure_of_potential       VARCHAR(100),
  number_of_copies           INT           DEFAULT 0,
  period_of_contract         VARCHAR(50),
  potential_count            INT           DEFAULT 0,
  type_of_model              VARCHAR(50),
  industry_type              VARCHAR(100),
  industry_sub_category      VARCHAR(100),
  day_of_delivery            VARCHAR(50),
  final_scheme_count         INT           DEFAULT 0,
  toi   INT DEFAULT 0,
  et    INT DEFAULT 0,
  etw   INT DEFAULT 0,
  mm    INT DEFAULT 0,
  mt    INT DEFAULT 0,
  nbt   INT DEFAULT 0,
  am    INT DEFAULT 0,
  bm    INT DEFAULT 0,
  bbm   INT DEFAULT 0,
  pm    INT DEFAULT 0,
  st    INT DEFAULT 0,
  vke   INT DEFAULT 0,
  sf_lead_id                 VARCHAR(36),
  lead_id                    VARCHAR(50),
  lead_auto_number           VARCHAR(50),
  description                TEXT,
  created_by                 VARCHAR(100),
  created_at                 TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  updated_at                 TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Verify table was created
SELECT COUNT(*) AS column_count FROM information_schema.columns
WHERE table_schema = 'CRMRMD' AND table_name = 'leads';
