-- Run in MySQL Workbench connected to your RDS instance
-- Creates CRMRMD.users with all Salesforce User fields + app login fields

CREATE TABLE IF NOT EXISTS CRMRMD.users (
  -- Primary key (Salesforce 18-char ID or UUID for local users)
  id                                  VARCHAR(36)   NOT NULL PRIMARY KEY,

  -- Salesforce standard fields
  username                            VARCHAR(200),
  last_name                           VARCHAR(100),
  first_name                          VARCHAR(100),
  name                                VARCHAR(200),
  company_name                        VARCHAR(200),
  division                            VARCHAR(100),
  department                          VARCHAR(100),
  title                               VARCHAR(100),
  street                              VARCHAR(255),
  city                                VARCHAR(100),
  state                               VARCHAR(100),
  postal_code                         VARCHAR(20),
  country                             VARCHAR(100),
  latitude                            DECIMAL(10,8),
  longitude                           DECIMAL(11,8),
  geocode_accuracy                    VARCHAR(50),
  address                             TEXT,
  email                               VARCHAR(200),
  is_active                           TINYINT(1)    DEFAULT 1,
  timezone_sid_key                    VARCHAR(50),
  user_role_id                        VARCHAR(36),
  locale_sid_key                      VARCHAR(20),
  receives_info_emails                TINYINT(1)    DEFAULT 0,
  receives_admin_info_emails          TINYINT(1)    DEFAULT 0,
  email_encoding_key                  VARCHAR(20),
  profile_id                          VARCHAR(36),
  user_type                           VARCHAR(50),
  start_day                           INT,
  end_day                             INT,
  language_locale_key                 VARCHAR(20),
  employee_number                     VARCHAR(50),
  delegated_approver_id               VARCHAR(36),
  manager_id                          VARCHAR(36),
  last_login_date                     DATETIME,
  last_password_change_date           DATETIME,
  sf_created_date                     DATETIME,
  sf_created_by_id                    VARCHAR(36),
  sf_last_modified_date               DATETIME,
  sf_last_modified_by_id              VARCHAR(36),
  system_modstamp                     DATETIME,
  password_expiration_date            DATETIME,
  number_of_failed_logins             INT           DEFAULT 0,
  has_user_verified_phone             TINYINT(1)    DEFAULT 0,
  has_user_verified_email             TINYINT(1)    DEFAULT 0,
  is_partner                          TINYINT(1)    DEFAULT 0,
  contact_id                          VARCHAR(36),
  account_id                          VARCHAR(36),
  call_center_id                      VARCHAR(36),
  extension                           VARCHAR(50),
  portal_role                         VARCHAR(50),
  is_portal_enabled                   TINYINT(1)    DEFAULT 0,
  federation_identifier               VARCHAR(100),
  about_me                            TEXT,
  full_photo_url                      VARCHAR(500),
  small_photo_url                     VARCHAR(500),
  is_ext_indicator_visible            TINYINT(1)    DEFAULT 0,
  out_of_office_message               VARCHAR(500),
  medium_photo_url                    VARCHAR(500),
  digest_frequency                    VARCHAR(10),
  default_group_notification_freq     VARCHAR(10),
  last_viewed_date                    DATETIME,
  last_referenced_date                DATETIME,
  banner_photo_url                    VARCHAR(500),
  small_banner_photo_url              VARCHAR(500),
  medium_banner_photo_url             VARCHAR(500),
  is_profile_photo_active             TINYINT(1)    DEFAULT 0,
  individual_id                       VARCHAR(36),

  -- RMD custom fields
  account_name                        VARCHAR(200),
  rmd_bp_id                           VARCHAR(50),
  rmd_freeze_date                     DATE,
  rmd_is_adsa                         TINYINT(1)    DEFAULT 0,
  rmd_is_deos                         TINYINT(1)    DEFAULT 0,
  rmd_is_deo                          TINYINT(1)    DEFAULT 0,
  rmd_is_dsa                          TINYINT(1)    DEFAULT 0,
  rmd_is_tcs                          TINYINT(1)    DEFAULT 0,
  rmd_is_tc                           TINYINT(1)    DEFAULT 0,
  archival_completed                  TINYINT(1)    DEFAULT 0,
  target_branch                       VARCHAR(36),
  show_refund                         TINYINT(1)    DEFAULT 0,
  mobile_id                           VARCHAR(50),

  -- App authentication
  password_hash                       VARCHAR(255),
  created_at                          TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
  updated_at                          TIMESTAMP     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  UNIQUE KEY uq_email    (email),
  UNIQUE KEY uq_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- Verify
SELECT COUNT(*) AS column_count
FROM information_schema.columns
WHERE table_schema = 'CRMRMD' AND table_name = 'users';
